baseURL = "https://is-club.github.io/"
languageCode = "ja-jp"
DefaultContentLanguage = "ja"
title = "Information Science Club"
author = "ISC Staff"
copyright = "Information Science Club"
theme = "hello-friend-ng"
hasCJKLanguage = true
googleAnalytics = "G-K70D9KPZJ6"

[params]
    homeSubtitle = "情報と共存する"

[menu]

  [[menu.main]]
    identifier = "su"
    name = "Study Unit"
    url = "/su/"
    weight = 10

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/categories/"
    weight = 15
